### ISSUE TITLE
The Website does not check if it's alpha numeric and 20 digit sometimes

### ISSUE THREAD

**Issue by mohithgupta** [sumitkolhe/krates#1]
I was able to create Krates with ID's = "123456789-12345678_9" and "thefficienttodowebapp" 

But I cannot delete them now because the Error says "The Id should be alphanumeric" and "Id should have a length of 20 characters" for the respective IDs

It's pretty funny that it lets us create but not delete due to the restrictions on ID itself 😂

I hope you resolve it ASAP 🙃 (and also delete the above mentioned krates if possible)

By the way, thanks for creating this man! It's a gem, but I don't know why no one out there knows about this!

![Screenshot (276)](https://user-images.githubusercontent.com/50448748/147846778-0adc1275-736e-4c14-8787-77c2dda0166f.png)

![Screenshot (277)](https://user-images.githubusercontent.com/50448748/147846795-8be80070-8532-4fb8-9429-2a1fc33d12b5.png)

**Comment by sumitkolhe** [comment]
@mohithgupta thanks for the bug report, i'll try to fix it ASAP. Also, if you like the app do share it with others :)

**Comment by mohithgupta** [comment]
Hey @sumitkolhe, I wanted to request a feature - It would be better to have authentication for accessing the dashboard, else there is no possible way to access all my krates from other devices unless I have all those krate IDs which would practically be a burden.  
Btw, Happy New Year mate!

**Comment by sumitkolhe** [comment]
@mohithgupta I agree, without per-user auth, its hard to keep track of all the data you've saved in krat.es till now. This was a decision I had to make when building the platform, whether to keep it open and be "auth-less" or to go with a full fledged auth system. I went with the former one since the goal was to make it as fast and easy as possible to access and store data, but i do agree, public krates are prone to be deleted by unauthorized access. 

I would be introducing auth in v2, which will be coming soon! no ETAs as of now though :)

**Comment by mohithgupta** [comment]
@sumitkolhe Yeah, I completely agree. "Auth" thing is a pain that I'm going through now due to my side project haha.
I was very curious about how you started this project and how long it took and how did you build it and so on.....
Anyhow, Good Luck mate! Looking forward for v2 !!

**Comment by sumitkolhe** [comment]
bug fixed in this [commit](https://github.com/sumitkolhe/krates/commit/d1bd5f1f54cc3a944be0fea38fb6940923d777f1)
